name: Scan TF
on:
  workflow_dispatch:
  
jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - run: git config --global url."https://nikpivkin:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com
      
      - name:  Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'

      - name: Upload Trivy scan results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
